apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l4m8os6ec-go 
  janus-idp.io/tekton: l4m8os6ec-go
  backstage.io/kubernetes-id: l4m8os6ec-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l4m8os6ec-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml