apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l4m8os6ec-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l4m8os6ec-go 
  name: l4m8os6ec-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: l4m8os6ec-go 
